/**
 * @file Words
 * @author Dino <dinoabsoluto+dev@gmail.com>
 * @license
 * This file is part of Translator Toolkit.
 *
 * Translator Toolkit is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Translator Toolkit is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Translator Toolkit.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
/* imports */
/* exports */
export const map: { [id: string]: string } = {
  /* priorities */
  'r15': 'R15',
  /* genres */
  '恋愛': 'love',
  '異世界': 'other world',
  '現実世界': 'real world',
  'ファンタジー': 'fantasy',
  'ハイファンタジー': 'high fantasy',
  'ローファンタジー': 'low fantasy',
  '文芸': 'literature',
  '純文学': 'pure literature',
  'ヒューマンドラマ': 'human drama',
  '歴史': 'history',
  '推理': 'reasoning',
  'ホラー': 'horror',
  'アクション': 'action',
  'コメディー': 'comedy',
  'SF': 'SF',
  'VRゲーム': 'VR game',
  '宇宙': 'space',
  '空想科学': 'sci-fi',
  'パニック': 'panic',
  'その他': 'others',
  '童話': 'children story',
  '詩': 'song',
  'エッセイ': 'essay',
  'リプレイ': 'replay',
  'ノンジャンル': 'no genre',
  /* standard keywords */
  'ギャグ': 'gag',
  'ギャグ要素': 'gag elements',
  'シリアス': 'serious',
  'ほのぼの': 'heartwarming',
  'ダーク': 'dark',
  '男主人公': 'male protagonist',
  '女主人公': 'female protagonist',
  '人外': 'none-human',
  '魔王': 'demon king',
  '勇者': 'the brave',
  '和風': 'Japanese style',
  '西洋': 'Western',
  '西洋風': 'Western style',
  '中華': 'China',
  '中華風': 'China style',
  '学園': 'school',
  '戦国': 'Warring States',
  '幕末': 'Bakumatsu',
  '明治': 'Meiji era',
  '大正': 'Taishō era',
  '明治/大正': 'Meiji/Taishō era',
  '昭和': 'Showa era',
  '平成': 'Heisei era',
  '古代': 'Ancient times',
  '中世': 'Middle Ages',
  '中世ヨーロッパ': 'Middle Ages Europe',
  '中世ヨーロッパ風': 'Middle Ages Europe style',
  '近世': 'early modern',
  '近代': 'modern',
  '現代': 'present',
  '未来': 'future',
  'ロボット': 'robot',
  'アンドロイド': 'android',
  '職業もの': 'jobs',
  'ハーレム': 'harem',
  '逆ハーレム': 'reverse-harem',
  '群像劇': 'multi protagonists',
  'チート': 'cheat',
  '内政': 'dosmetic affairs',
  '魔法': 'magic',
  '冒険': 'adventure',
  'ミリタリー': 'military',
  '日常': 'everyday',
  'ハッピーエンド': 'happy ending',
  'バッドエンド': 'bad ending',
  'グルメ': 'gourmet',
  '青春': 'youth',
  'ゲーム': 'game',
  '超能力': 'ESP',
  'タイムトラベル': 'time travel',
  'ダンジョン': 'dungeon',
  'パラレルワールド': 'parallel world',
  'タイムリープ': 'time leap',
  '異類婚姻譚': 'interracial marriage',
  '身分差': 'social status difference',
  '年の差': 'age difference',
  '悲恋': 'blighted love',
  'ヒストリカル': 'historical',
  '乙女ゲーム': 'maiden game',
  '悪役令嬢': 'villainess',
  'オフィスラブ': 'office romance',
  'スクールラブ': 'school romance',
  '古典恋愛': 'classic rommance',
  'オリジナル戦記': 'original war chronicle',
  '伝奇': 'romance (fiction)',
  // 'ヒューマンドラマ': 'human drama',
  'ハードボイルド': 'hard-boiled',
  '私小説': '1st person narrator',
  'ホームドラマ': 'soap opera',
  'IF戦記': 'What-if war chronicle',
  '史実': 'historical fact',
  '時代時代小説': 'historical novel',
  '逆行転生': 'backward reincarnation',
  'ミステリー': 'mystery',
  'サスペンス': 'suspense',
  '探偵小説': 'detective',
  'スプラッタ': 'splatter',
  '怪談': 'ghost story',
  'サイコホラー': 'spycho horror',
  '異能力バトル': 'abnormal power battle',
  'ヒーロー': 'hero',
  'スパイ': 'spy',
  // '冒険': 'adventure',
  'ラブコメ': 'rom-com',
  '近未来': 'near future',
  '人工知能': 'AI',
  '電脳世界': 'cyber world',
  // 'VRMMO': 'VRMMO',
  'スペースオペラ': 'space opera',
  'エイリアン': 'alient',
  'サイバーパンク': 'cyberpunk',
  'スチームパンク': 'steampunk',
  'ディストピア': 'dystopia',
  'タイムマシン': 'time machine',
  '怪獣': 'giant monster',
  '天災': 'disaster',
  'バイオハザード': 'biohazard',
  'パンデミック': 'pandemic',
  'サバイバル': 'survival',
  // more keywords
  '残酷な描写あり': 'cruel depiction',
  '転生': 'reincarnation',
  '生まれ変わり': 'reborn',
  '異世界召喚': 'otherworld summon',
  '異世界転生': 'otherworld reincarnation',
  'モブキャラ転生': 'mob-character reincarnation',
  '魔物転生': 'monster reincarnation',
  'クラス転移': 'class teleport',
  '異世界転移': 'otherworld teleport',
  '主人公最強': 'strongest protagonist',
  '仲間最強': 'strongest comrade',
  '不信の主人公': 'distrustful protagonist',
  '俺tueee': 'I\'m STRONG',
  '仲間tueee': 'comrade\'s STRONG',
  '中二病': 'chunnibyou',
  '一人称': '1st person',
  '鬼畜': 'brute',
  '不器用': 'clumsy',
  'オリジナル': 'original',
  '要素': 'factors',
  // '多数': 'lots',
  // theme
  'つまらない': 'tedious',
  'ありきたり': 'common',
  'パロ': 'parody',
  'テンプレ': 'template',
  'シュール': 'surreal',
  'どん底': 'bottom',
  '成り上がり': 'upstart',
  '立ち向かう': 'oppose',
  'ご都合主義': 'opportunism',
  '滅亡回避': 'downfall evasion',
  'ざまぁ': 'serve you right!',
  'お料理': 'cooking',
  'もふもふ': 'mofumofu',
  'スローライフ': 'slow life',
  '貧乏': 'poverty',
  'ドタバタ': 'slapstick',
  '勘違い': 'misunderstanding',
  // 'すれ違い': 'passing each other',
  '迷宮': 'labyrinth',
  '不老不死': 'perpetual youth',
  'あべこべ': 'inversed',
  'スポーツ': 'sport',
  '部活': 'clubs',
  '最強': 'strongest',
  '最恐': 'scariest',
  '無双': 'peerless',
  '無能力': 'incompetence',
  '記憶喪失': 'amnesia',
  '時間停止': 'time stop',
  '旅': 'travel',
  '不良': 'delinquent',
  '頭脳': 'intelectual',
  '勇者召喚': 'hero summoning',
  // state
  'ゆっくり': 'restful',
  'サクサク': 'quickly',
  // negative, comback
  '不遇': 'misfortuned',
  '失格': 'disqualified',
  '廃嫡': 'disinherited',
  '逆転': 'reversal',
  '報われる努力': 'rewarded effort',
  '絶望': 'despair',
  '追放': 'exile',
  '裏切り': 'betrayal',
  '復讐': 'revenge',
  '陰謀': 'conspiracy',
  '人体実験': 'human experiment',
  // cautions
  'グロ注意': 'GROSTESQUE CAUTION',
  // management
  '建国': 'kingdom founding',
  '国家運営': 'country management',
  '経済': 'economics',
  '外交': 'diplomacy',
  '戦争': 'war',
  '戦略': 'strategy',
  '戦術': 'tactics',
  '商品売買': 'product trading',
  '葛藤': 'conflict',
  // location
  '魔術学校': 'magic school',
  '魔法学園': 'magic academy',
  '学園都市': 'university town',
  'ゲームの世界': 'game world',
  '現代社会': 'modern society',
  '教会': 'church',
  'ギルド': 'guild',
  '冒険者ギルド': 'adventurer guild',
  // system
  'vrmmo': 'VRMMO',
  'アイテムボックス': 'item box',
  'ステータス': 'status',
  'スキル': 'skill',
  'ステータスとスキル': 'status & skill',
  'sssランク': 'SSS-rank',
  'エロゲ': 'ero-game',
  '成長': 'growth',
  '進化': 'evolution',
  '変化': 'mutation',
  // objects
  '攻略本': 'strategy guide',
  'エクスカリバー': 'Excalibur',
  'チート商品': 'cheat items',
  '武器': 'weapon',
  '防具': 'armor',
  '魔剣': 'magic sword',
  '聖剣': 'holy sword',
  '銃': 'gun',
  '飛行船': 'airship',
  'カクテル': 'cocktail',
  // combat
  'バトル': 'battle',
  '盾': 'shield',
  '剣': 'sword',
  '魔力': 'magic power',
  '物理攻撃': 'physical attack',
  '魔法攻撃': 'magical attack',
  // '魔法': 'magic',
  '剣と魔法': 'sword & magic',
  '剣士': 'swordman',
  '魔導': 'sorcery',
  '魔術': 'wizardry',
  '剣術': 'swordmanship',
  '死魔法': 'necromancy',
  '武術': 'martial art',
  '陰陽師': 'onmyouji',
  '陰陽道': 'yin & yang',
  '式神': 'shikigami',
  '格闘技': 'unarmed combat',
  '召喚': 'summon',
  '召喚士': 'summoner',
  '希少職': 'rare job',
  '錬金術師': 'alchemist',
  // species
  'モンスター': 'MONSTER',
  'スライム': 'SLIME',
  'ドラゴン': 'DRAGON',
  'ゴーレム': 'GOLEM',
  'ネクロマンサー': 'NECROMANCER',
  '魔物': 'magical being',
  '魔獣': 'magic beast',
  '妖怪': 'youkai',
  '天狗': 'tengu',
  '精霊': 'spirit',
  '幽霊': 'spectre',
  '吸血鬼': 'vampire',
  '獣人': 'beastfolk',
  '人狼': 'werewolf',
  'ドワーフ': 'DWARF',
  'エルフ': 'ELF',
  'ダークエルフ': 'DARK ELF',
  '人造人間': 'artificial human',
  '魔族': 'demonfolk',
  // characters: male
  'おっさん': 'ossan',
  'ヒモ': 'gigolo',
  '王': 'king',
  '王様': 'king',
  '王子': 'prince',
  '執事': 'butler',
  // characters: neutral
  'マスター': 'MASTER',
  'ゲーマー': 'GAMER',
  'バーサーカー': 'BERSERKER',
  '脇役': 'supporting role',
  '神': 'god',
  '転生者': 'reincarnator',
  '暗殺者': 'assassin',
  '公爵': 'duke',
  '貴族': 'noble',
  '騎士': 'knight',
  '冒険者': 'adventurer',
  'Sランク冒険者': 'S-rank adventurer',
  '奴隷': 'slave',
  '英雄': 'hero',
  '教師': 'teacher',
  '先生': 'sensei',
  '高校生': 'highschooler',
  '魔法使い': 'magician',
  '魔導師': 'sorcerer',
  '最強魔導士': 'strongest sorcerer',
  'テイマー': 'tamer',
  '従魔': 'tamed creatures',
  '賢者': 'sage',
  '剣聖': 'sword saint',
  '大隊長': 'battalion commander',
  '幼馴染': 'childhood friend',
  // characters: female
  'ヒロイン': 'heroine',
  '女神': 'goddess',
  '女神さま': 'goddess',
  '天使': 'angel',
  '聖女': 'saintess',
  '姫': 'hime',
  '王女': 'princess',
  '女公爵': 'duchess',
  '公爵令嬢': 'duke ojou-sama',
  '令嬢': 'ojou-sama',
  '女騎士': 'female knight',
  '魔女': 'witch',
  '魔法少女': 'magical girl',
  'メイド': 'maid',
  '女教師': 'female teacher',
  '少女': 'girl',
  '幼女': 'little girl',
  '女性': 'woman',
  '美少女': 'beautiful girl',
  '合法ロリ': 'legal loli',
  'モン娘': 'monster girl',
  '猫耳娘': 'cat ears girl',
  'ギャル': 'gyaru',
  'ビッチ': 'bitch',
  // characters: family
  'パパ': 'papa',
  'ママ': 'mama',
  '父': 'father',
  '父さん': 'father',
  'お父さん': 'father',
  '母': 'mother',
  '母さん': 'mother',
  'お母さん': 'mother',
  '娘': 'daughter',
  '娘さん': 'daughter',
  'お娘さん': 'daughter',
  '母娘': 'mother and daughter',
  '母息子': 'mother and son',
  '息子': 'son',
  '息子さん': 'son',
  '兄妹': 'older brother and younger sister',
  '姉': 'big sister',
  '姉さん': 'big sister',
  'お姉さん': 'big sister',
  '姉弟': 'big sister and little brother',
  '妹': 'younger sister',
  '妹さん': 'younger sister',
  'お妹さん': 'younger sister',
  '兄弟': 'brothers',
  '姉妹': 'sisters',
  '姪': 'niece',
  '姪っ子': 'niece',
  '嫁': 'wife',
  '嫁さん': 'wife',
  'お嫁さん': 'wife',
  // love: romance
  '百合': 'yuri',
  'ガールズラブ': 'girls love',
  'ボーイズラブ': 'boys love',
  '三角関係': 'love triangle',
  '禁断の恋': 'forbidden love',
  '溺愛': 'blind love',
  '婚約': 'engagement',
  '婚約破棄': 'engagement discarded',
  '運命': 'destiny',
  '婚活': 'marriage hunting',
  'ツンデレ': 'tsundere',
  '鈍感主人公': 'thickheaded protagonist',
  '学園コメディ': 'school comedy',
  'ブラコン': 'brocon',
  'シスコン': 'siscon',
  'らぶらぶ': 'lovey-dovey',
  '女性視点': 'girl point-of-view',
  'ショタ': 'shota',
  'ロリ': 'loli',
  'エロ': 'ero',
  '寝取られ': 'cuckolding',
  'ネトラレ': 'cuckolding',
  // love: family
  '親馬鹿': 'doting parent',
  '家族愛': 'family love',
  // others
  '音楽': 'music',
  'お花畑': 'flower field',
  '植物学': 'botany',
  '地質学': 'geology',
  'ライトノベル': 'light novel',
  'コミカライズ': 'comic adaptation',
  '書籍化': 'book adaptation',
  '短編集': 'short stories collection',
  '豆知識': 'trivia'
}
